# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('community_string', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('vlan', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('device_name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('uptime_seconds', models.IntegerField(blank=True, null=True)),
                ('device_group', models.CharField(max_length=50)),
                ('last_scan', models.DateTimeField()),
                ('credentials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='send_command.Credentials')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('data_vlan', models.IntegerField(default=1)),
                ('voice_vlan', models.IntegerField(default=1)),
                ('management_vlan', models.IntegerField(default=1)),
                ('site_group', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_command.Site'),
        ),
    ]
