# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_command', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='data_vlan',
        ),
        migrations.RemoveField(
            model_name='site',
            name='management_vlan',
        ),
        migrations.RemoveField(
            model_name='site',
            name='voice_vlan',
        ),
        migrations.AddField(
            model_name='interface',
            name='speed',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='data_vlan',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='management_vlan',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='voice_vlan',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='interface',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='vlan',
            field=models.IntegerField(default=1),
        ),
    ]
