# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_command', '0002_auto_20160313_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='device_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='ip_address',
            field=models.GenericIPAddressField(primary_key=True, serialize=False),
        ),
    ]
