# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_command', '0003_auto_20160314_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='last_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='port',
            field=models.IntegerField(default=22),
        ),
    ]
