# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_command', '0004_auto_20160314_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvfile', models.FileField(upload_to='downloads/')),
            ],
        ),
    ]
