# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 02:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentactions',
            name='action',
        ),
        migrations.AddField(
            model_name='recentactions',
            name='input_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 16, 2, 36, 5, 650759), null=True),
        ),
    ]
