# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20160316_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactions',
            name='input_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
