# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 03:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20160316_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentactions',
            name='entry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recentactions',
            name='input_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 16, 3, 39, 32, 584203, tzinfo=utc)),
        ),
    ]
