# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 04:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20160316_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('community_string', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('vlan', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1000)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('device_name', models.CharField(max_length=80)),
                ('device_type', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('port', models.IntegerField(default=22)),
                ('data_vlan', models.IntegerField(default=1)),
                ('voice_vlan', models.IntegerField(default=1)),
                ('management_vlan', models.IntegerField(default=1)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('uptime_seconds', models.IntegerField(blank=True, null=True)),
                ('device_group', models.CharField(max_length=50)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('credentials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Credentials')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('site_group', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='recentactions',
            name='input_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 16, 4, 8, 15, 678489, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Site'),
        ),
    ]
