# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20160316_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_credentails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Credentials'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_template',
            field=models.FileField(blank=True, null=True, upload_to='template/'),
        ),
        migrations.AlterField(
            model_name='recentactions',
            name='input_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 16, 5, 9, 48, 779846, tzinfo=utc)),
        ),
    ]
