# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 05:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20160316_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_credentails',
            new_name='site_credentials',
        ),
        migrations.AlterField(
            model_name='recentactions',
            name='input_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 16, 5, 11, 6, 490525, tzinfo=utc)),
        ),
    ]
